name: ecommerceapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  provider: ^6.1.5+1
  flutter_svg: ^2.2.0
  http: ^1.5.0
  google_sign_in: ^6.2.0 
  flutter_facebook_auth: ^7.1.2
  supabase_flutter: ^2.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.0
  cloudinary: ^1.2.0
  cloudinary_public: ^0.23.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/svgs/
    - assets/images/logo.png
    - assets/svgs/shirt.svg
    - assets/svgs/notebook.svg
    - assets/svgs/laptop.svg
    - assets/svgs/furniture.svg
    - assets/images/auction.png
    - assets/images/group.png
    - assets/images/store.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
          style: italic
    - family: Poesten-One
      fonts:
        - asset: assets/fonts/Poesten-One/PoetsenOne-Regular.ttf      
